export enum LeagueStatus {
  PENDING = 'PENDING',
  SETUP = 'SETUP',
  DRAFTING = 'DRAFTING',
  POST_DRAFT = 'POST_DRAFT',
  TRANSFER_WINDOW = 'TRANSFER_WINDOW',
  REGULAR_SEASON = 'REGULAR_SEASON',
  POST_REGULAR_SEASON = 'POST_REGULAR_SEASON',
  PLAYOFFS = 'PLAYOFFS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
